#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

# --- Calendar feed helpers -------------------------------------------------
# Google serves each calendar as an iCal feed at a secret address. These check
# a pasted address before it is saved, without ever printing the secret part.

# ical_calendar_id URL prints which calendar an address belongs to.
ical_calendar_id() {
  local prefix="https://calendar.google.com/calendar/ical/" rest
  if [[ "$1" == "$prefix"* ]]; then
    rest="${1#"$prefix"}"
    rest="${rest%%/*}"
    rest="${rest//%40/@}"
    printf '%s' "${rest//%23/#}"
  else
    rest="${1#*://}"
    printf '%s' "${rest%%/*}"
  fi
}

# ical_event_count URL fetches the feed and prints how many events it holds.
# Fails if the address does not return a calendar.
ical_event_count() {
  local body
  body=$(curl -fsS --max-time 20 "$1" 2>/dev/null) || return 1
  [[ "$body" == BEGIN:VCALENDAR* ]] || return 1
  printf '%s\n' "$body" | grep -c '^BEGIN:VEVENT' || true
}

# check_ical URL succeeds if the address should be saved.
check_ical() {
  local url="$1" count
  if [[ "$url" == https://calendar.google.com/*/public/* ]]; then
    warn "That is the public address, which only works for a calendar shared"
    warn "publicly. Copy 'Secret address in iCal format' instead."
    return 1
  fi
  if command -v curl >/dev/null 2>&1; then
    if count=$(ical_event_count "$url"); then
      printf '  %s✓%s %s: %s events\n' "$GREEN" "$RESET" "$(ical_calendar_id "$url")" "$count"
      return 0
    fi
    warn "That address did not return a calendar."
    note "Check the whole address was copied. A reset address stops working at once."
  elif [[ "$url" =~ ^https://calendar\.google\.com/calendar/ical/[^/]+/private-[^/]+/basic\.ics$ ]]; then
    note "curl is not installed, so the address was not checked, but it has the right shape."
    return 0
  else
    warn "That does not look like a Google secret iCal address, and curl is not"
    warn "installed to check it."
  fi
  confirm "Save it anyway?"
}
# --- end calendar feed helpers ---------------------------------------------

# --- TickTick helpers ------------------------------------------------------
# check_ticktick TOKEN succeeds if the token should be saved. The token is fed
# to curl on stdin rather than as an argument, so it never shows up in `ps`.
check_ticktick() {
  local token="$1" body lists
  if ! command -v curl >/dev/null 2>&1; then
    note "curl is not installed, so the token was not checked."
    return 0
  fi
  if ! body=$(printf 'Authorization: Bearer %s' "$token" |
      curl -fsS --max-time 20 -H @- https://api.ticktick.com/open/v1/project 2>/dev/null); then
    warn "TickTick rejected that token."
    note "Copy it again, or create a new one on the same page."
    confirm "Save it anyway?"
    return
  fi
  lists=$(printf '%s' "$body" | grep -o '"name"' | wc -l | tr -d ' ')
  printf '  %s✓%s token works: %s lists on the account\n' "$GREEN" "$RESET" "$lists"
  if ! printf '%s' "$body" | grep -q 'To-Do'; then
    warn "No list with 'To-Do' in its name was found. If the shared list is"
    warn "called something else, set ticktick.listName in config.yaml."
  fi
  return 0
}
# --- end TickTick helpers --------------------------------------------------

TOTAL_STAGES=4

banner "Home dashboard setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Google Calendar: secret iCal addresses"
say "The calendar widget reads each calendar from its secret iCal address, a"
say "private link Google serves your events from. No Google Cloud project, no"
say "OAuth app, no sign-in."
note "The trade-off is read-only: adding events from the wall needs OAuth,"
note "which is parked in FUTURE.md."
printf '\n'
warn "Treat each address like a password: anyone who has it can read every"
warn "event on that calendar. If one leaks, reset it where you copied it from."
printf '\n'

ical_urls=()
existing_ical=$(_existing CALENDAR_ICAL_URLS || true)
if [[ -n "$existing_ical" ]]; then
  IFS=, read -ra saved_ical <<< "$existing_ical"
  say "Already saved:"
  for url in "${saved_ical[@]}"; do step "$(ical_calendar_id "$url")"; done
  if confirm "Keep these and skip ahead?"; then ical_urls=("${saved_ical[@]}"); fi
fi

if (( ${#ical_urls[@]} == 0 )); then
  open_url "https://calendar.google.com/calendar/r/settings"
  step "In the left sidebar, under 'Settings for my calendars', click a calendar."
  step "Scroll down to 'Integrate calendar'."
  step "Copy 'Secret address in iCal format', not the public address above it."
  while true; do
    ask_secret ICAL_URL "Paste the secret address (input is hidden):"
    if [[ -z "$ICAL_URL" ]]; then
      if (( ${#ical_urls[@]} )) || confirm "Skip the calendar for now?"; then break; fi
      continue
    fi
    check_ical "$ICAL_URL" || continue
    ical_urls+=("$ICAL_URL")
    confirm "Add another calendar?" || break
    step "Click the next calendar in the sidebar and copy its secret address."
  done
fi

if (( ${#ical_urls[@]} )); then
  write_env CALENDAR_ICAL_URLS "$(IFS=,; printf '%s' "${ical_urls[*]}")"
else
  SKIPPED+=("Calendar: re-run npm run setup to add a secret iCal address")
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "TickTick: personal API token"
say "The task widget reads and updates your shared list with a personal API"
say "token. No developer app, no sign-in."
printf '\n'
warn "The token can read and change everything in your TickTick account."
warn "Treat it like a password. If it leaks, revoke it where you created it."
printf '\n'
open_url "https://ticktick.com/webapp/"
step "Sign in with the account that belongs to the shared 🏡To-Do list."
step "Click your avatar (top left), then Settings > Account > API Token."
step "Create a token and copy it."
while true; do
  ask_secret TICKTICK_API_TOKEN "Paste the token (input is hidden):"
  if [[ -z "$TICKTICK_API_TOKEN" ]]; then
    if confirm "Skip TickTick for now?"; then break; fi
    continue
  fi
  if check_ticktick "$TICKTICK_API_TOKEN"; then break; fi
done
if [[ -n "$TICKTICK_API_TOKEN" ]]; then
  write_env TICKTICK_API_TOKEN "$TICKTICK_API_TOKEN"
else
  SKIPPED+=("TickTick: re-run npm run setup to add an API token")
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Kasa bulbs: find them on your network"
say "Bulb addresses go in config.yaml rather than .env, because they are"
say "settings rather than secrets. This scan has to run here on your network:"
say "Docker's default network does not carry the broadcast it uses."
pause "Make sure both bulbs are powered on at the wall, then press Enter."
printf '\n'
node scripts/find-kasa.mjs || true
printf '\n'
step "Reserve each address in your router (DHCP reservation / static lease),"
step "so a reboot does not renumber them."
step "Copy the 'lights:' block printed above into config.yaml."
note "A bulb that works in the Kasa app but did not appear has newer firmware"
note "that refuses local control. If that happens, say yes below."
if confirm "Any bulb missing that you need to control through TP-Link's cloud?"; then
  ask       KASA_USERNAME "TP-Link account email:"
  ask_secret KASA_PASSWORD "TP-Link account password:"
  write_env KASA_USERNAME "$KASA_USERNAME"
  write_env KASA_PASSWORD "$KASA_PASSWORD"
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Start the dashboard"
say "Everything is saved. Start the dashboard on your server:"
say  "    docker compose up -d"
printf '\n'
say "Then check every source is healthy:"
say  "    curl -s http://localhost:8080/api/health"
printf '\n'
say "On the iPad, open http://<your-server>:8080 in Safari, then use"
say "Share > Add to Home Screen so it runs full screen."
pause "Press Enter to finish."

finish
